---
- hosts: centos7
  any_errors_fatal: yes
  pre_tasks:
    - name: Include vars
      include_vars: vars.yml
  roles:
    - ansible-role-kafka-in-docker

- hosts: ubuntu18
  any_errors_fatal: yes
  pre_tasks:
    - name: Include vars
      include_vars: vars.yml
  roles:
    - ansible-role-kafka-in-docker
